version: '3.7'

services:

    client:
      build:
          context: ./frontend
          dockerfile: Dockerfile
      ports:
          - "3000:80"
      volumes: 
          - ./frontend:/app
          - /app/node_modules
      networks:
          - frontend

    postgresdb:
      image: "postgres:12"
      container_name: postgresdb
      env_file: 
        - ./backend/postgres.env
      ports:
        - 5432:5432
      volumes:
        - db_volume:/var/lib/postgresql/data
      networks:
      - backend

    api:
      build: 
          context: ./backend
          dockerfile: Dockerfile
      command: gunicorn --bind 0.0.0.0:5000 app:app
      expose:
          - 5000
      env_file: 
          - ./backend/api.env
      volumes:
          - appdata:/var/www/
      depends_on: 
          - postgresdb
      networks:
          - frontend
          - backend

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge

volumes:
  db_volume:
      driver: local
  appdata:
      driver: local